name: QuanlityInnovations SonarCloud GitHub Action
description: 'Scans, Quality Gates, PR Comments, and Annotations'

branding:
  icon: check-circle
  color: green

inputs: 

  args:
    description: Additional arguments to the SonarCloud scanner
    required: false

  teamName:
    description: 'The SonarQube team name'
    required: true
    default: 'team'

  projectBaseDir:
    description: 'The project base directory'
    required: false
    default: '.'

  sonarHostUrl:
    description: 'The SonarQube Host Url'
    required: false
    default: 'https://sonarcloud.io/'

  SONAR_TOKEN:
    description: 'SonarCloud or SonarQube authentication token'
    required: true

  fixPath:
    description: 'Fix the path in the Scoverage report'
    required: false
    default: 'false'

runs:
  using: composite
  steps:

    - name: Replace all working directory paths with sources path
      run: sed -i -e "s#${{ github.workspace }}#/github/workspace#g" $(grep -rl "${{ github.workspace }}" .)
      
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        args: ${{ inputs.args }}
      env:
        SONAR_HOST_URL: ${{ inputs.sonarHostUrl }}

    - name: SonarQube Quality Gate check
      uses: sonarsource/sonarqube-quality-gate-action@master
      id: sonarqube-quality-gate-check
      env:
        SONAR_HOST_URL: ${{ inputs.sonarHostUrl }}

    - name: SonarQube Quality Gate Comment
      id: sonarqube-quality-gate-comment
      shell: bash
      run: echo "Future Feature!"

    - name: "Example show SonarQube Quality Gate Status value"
      shell: bash
      run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
