name: QuanlityInnovations SonarQube GitHub Action
description: 'Scans, Quality Gates, PR Comments, and Annotations'

branding:
  icon: check-circle
  color: green

inputs:
  scoverageReport:
    description: 'The path to the Scoverage report in XML format'
    required: false

  args:
    description: 'Additional arguments to the SonarQube scanner'
    required: false

  teamName:
    description: 'The SonarQube team name'
    required: true
    default: 'team'

  projectBaseDir:
    description: 'The project base directory'
    required: false
    default: .

  SONAR_HOST_URL:
    description: 'The SonarQube Host Url'
    required: false
    default: 'https://sonarcloud.io/'

  SONAR_TOKEN:
    description: 'SonarQube authentication token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install SonarQube Scanner
      shell: bash
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonar-scanner-cli-4.6.2.2472-linux.zip
        mv sonar-scanner-4.6.2.2472-linux sonar-scanner
        echo "PATH=$(pwd)/sonar-scanner/bin:$PATH" >> $GITHUB_ENV

    - name: Run SonarQube Scanner
      shell: bash
      run: |
        sonar-scanner \
        -Dsonar.token="${{ inputs.SONAR_TOKEN }}" \
        -Dsonar.host.url="${{ inputs.SONAR_HOST_URL }}" \
        -Dsonar.projectBaseDir="${{ inputs.projectBaseDir }}" \
        -Dsonar.qualitygate.wait=true \
        -Dsonar.qualitygate.timeout=300 \
        ${{ inputs.args }}
